services:
  - type: web
    name: wikijs-app
    runtime: docker
    plan: free
    port: 3000
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        value: ep-fragrant-bird-apsm2o2y-pooler.c-7.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASS
        value: npg_z0d9ClEvZaRx
      - key: DB_NAME
        value: neondb
      - key: DB_SSL
        value: "true"
