services:
  - type: web
    name: wikijs-app
    runtime: node
    plan: free
    buildCommand: npm install --production --legacy-peer-deps
    startCommand: node server
    port: 3000
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: wikijs-db
          property: connectionString

databases:
  - name: wikijs-db
    plan: free
    databaseName: wikijs
    user: wikijs_user
